spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_jpa?serverTimezone=Asia/Shanghai
    username: root
    password: adccaims2019
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
#    hibernate:
#      ddl-auto: update
server:
  servlet:
    session:
      cookie:
        name: authorization
  port: 1234

logging:
  level:
    org.springframework.security: info
    org.springframework.security.oauth2: trace