spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_jpa?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 3000
  jpa:
    show-sql: true
    open-in-view: true
#    hibernate:
#      ddl-auto: update
#  redis:
#    host: 192.168.243.87
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    session:
      cookie:
        name: authorization
  port: 1234

logging:
  level:
    org.springframework.security: info
    org.springframework.security.oauth2: trace