spring:
  datasource:
    url: jdbc:mysql://192.168.243.87:3306/security_oauth2?serverTimezone=GMT
    username: root
    password: adccaims2019
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    session:
      cookie:
        name: authorization
  port: 1234

logging:
  level:
    org.springframework.security: info
    org.springframework.security.oauth2: trace
mybatis:
  mapper-locations: classpath:mybatis-mappers/*